[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ua-symphony"
version = "1.0.0"
description = "Static User-Agent collection"
requires-python = ">=3.7"

